export const ccaGenericData = {
  "ART AND CRAFTS": "Art And Crafts",
  "ENGLISH LANGUAGE DRAMA AND DEBATING": "English Language Drama And Debating",
  "INFOCOMM TECHNOLOGY (COMPUTING)": "Infocomm Technology (Computing)",
  "DESIGN AND INNOVATION": "Design And Innovation",
  "ENVIRONMENTAL SCIENCE": "Environmental Science",
  FOOTBALL: "Football",
  "TRACK AND FIELD": "Track And Field",
  WUSHU: "Wushu",
  "ROPE SKIPPING": "Rope Skipping",
  SCOUTS: "Scouts",
  "GIRL GUIDES (BROWNIES)": "Girl Guides (Brownies)",
  CHOIR: "Choir",
  "GUITAR ENSEMBLE": "Guitar Ensemble",
  "CHINESE DANCE": "Chinese Dance",
  "INDIAN DANCE": "Indian Dance",
  "MALAY DANCE": "Malay Dance",
  PHOTOGRAPHY: "Photography",
  BADMINTON: "Badminton",
  NETBALL: "Netball",
  RUGBY: "Rugby",
  "NATIONAL POLICE CADET CORPS": "National Police Cadet Corps",
  "NATIONAL CADET CORPS (LAND)": "National Cadet Corps (Land)",
  "NATIONAL CIVIL DEFENCE CADET CORPS": "National Civil Defence Cadet Corps",
  "MODERN DANCE": "Modern Dance",
  "ENGLISH DRAMA": "English Drama",
  "CONCERT BAND": "Concert Band",
  ROBOTICS: "Robotics",
  "DIGITAL MEDIA": "Digital Media",
  "GUZHENG ENSEMBLE": "Guzheng Ensemble",
  VOLLEYBALL: "Volleyball",
  "ANGKLUNG/KULINTANG ENSEMBLE": "Angklung/Kulintang Ensemble",
  "HARMONICA ENSEMBLE": "Harmonica Ensemble",
  "GIRL GUIDES": "Girl Guides",
  "ST JOHN BRIGADE": "St John Brigade",
  "CHINESE ORCHESTRA": "Chinese Orchestra",
  "BAND - SYMPHONIC": "Band - Symphonic",
  "DANCE - INTERNATIONAL": "Dance - International",
  "GREEN CLUB": "Green Club",
  SHOOTING: "Shooting",
  BASKETBALL: "Basketball",
  "TABLE TENNIS": "Table Tennis",
  "ARTISTIC GYMNASTICS": "Artistic Gymnastics",
  "CHINESE DRUMS": "Chinese Drums",
  "CHINESE CULTURE AND LANGUAGE": "Chinese Culture And Language",
  "INFOCOMM TECHNOLOGY (MEDIA PRODUCTION)":
    "Infocomm Technology (Media Production)",
  SOFTBALL: "Softball",
  TCHOUKBALL: "Tchoukball",
  "INTERNATIONAL CHESS": "International Chess",
  CHEERLEADING: "Cheerleading",
  FLOORBALL: "Floorball",
  "HANDBELL ENSEMBLE": "Handbell Ensemble",
  "BOYS' BRIGADE": "Boys' Brigade",
  "GIRLS' BRIGADE": "Girls' Brigade",
  "BRASS BAND": "Brass Band",
  "STUDENT LEADERSHIP (COUNCIL)": "Student Leadership (Council)",
  "BIOLOGICAL SCIENCE": "Biological Science",
  "AUDIO VISUAL AID": "Audio Visual Aid",
  "DEBATING AND PUBLIC SPEAKING": "Debating And Public Speaking",
  "SCIENCE SOCIETY": "Science Society",
  "VISUAL ARTS CLUB": "Visual Arts Club",
  HOCKEY: "Hockey",
  SQUASH: "Squash",
  TENNIS: "Tennis",
  TAEKWONDO: "Taekwondo",
  FRISBEE: "Frisbee",
  "POP AND JAZZ": "Pop And Jazz",
  "CHINESE LANGUAGE DRAMA AND DEBATING": "Chinese Language Drama And Debating",
  "INDIAN LANGUAGE DRAMA AND DEBATING": "Indian Language Drama And Debating",
  "TOUCH RUGBY": "Touch Rugby",
  "OUTDOOR ADVENTURE": "Outdoor Adventure",
  "ROCKWALL CLIMBING": "Rockwall Climbing",
  "COMMUNITY SERVICE (FIRST AID)": "Community Service (First Aid)",
  "COMMUNITY SERVICE": "Community Service",
  "RED CROSS YOUTH": "Red Cross Youth",
  "NATIONAL CADET CORPS (AIR)": "National Cadet Corps (Air)",
  "CHINESE DRAMA": "Chinese Drama",
  ENTREPRENEURSHIP: "Entrepreneurship",
  "LIBRARY COUNCIL": "Library Council",
  CANOEING: "Canoeing",
  "CROSS COUNTRY": "Cross Country",
  SWIMMING: "Swimming",
  "WATER POLO": "Water Polo",
  BOWLING: "Bowling",
  GOLF: "Golf",
  "STRING ENSEMBLE": "String Ensemble",
  "COMMUNITY SERVICE (ROTARY-SPONSORED)":
    "Community Service (Rotary-Sponsored)",
  "NATIONAL CADET CORPS (SEA)": "National Cadet Corps (Sea)",
  PUBLICATION: "Publication",
  "PHYSICAL SCIENCE": "Physical Science",
  SAILING: "Sailing",
  "STUDENT LEADERSHIP (PREFECT)": "Student Leadership (Prefect)",
  JUDO: "Judo",
  SEPAKTAKRAW: "Sepaktakraw",
  "PERCUSSION ENSEMBLE": "Percussion Ensemble",
  "MEDIA RESOURCE CLUB": "Media Resource Club",
  "BAND - MILITARY": "Band - Military",
  "INNOVATION AND ENTERPRISE CLUB": "Innovation And Enterprise Club",
  "UKULELE ENSEMBLE": "Ukulele Ensemble",
  "SINGAPORE YOUTH FLYING CLUB": "Singapore Youth Flying Club",
  "CULTURAL DANCE": "Cultural Dance",
  "TAMIL DRAMA": "Tamil Drama",
  "MEDIA RESOURCE LIBRARY": "Media Resource Library",
  FENCING: "Fencing",
  "MALAY CULTURE AND LANGUAGE": "Malay Culture And Language",
  "CHINESE CALLIGRAPHY AND BRUSH PAINTING":
    "Chinese Calligraphy And Brush Painting",
  "STRATEGY GAMES": "Strategy Games",
  "HOME ECONOMICS": "Home Economics",
  "NEW MEDIA ARTS": "New Media Arts",
  "STUDENT LEADERSHIP (HOUSE)": "Student Leadership (House)",
  "STUDENTS' COUNCIL": "Students' Council",
  "MALAY LANGUAGE DRAMA AND DEBATING": "Malay Language Drama And Debating",
  "CHINESE INSTRUMENTAL ENSEMBLE": "Chinese Instrumental Ensemble",
  "RHYTHMIC GYMNASTICS": "Rhythmic Gymnastics",
  CERAMICS: "Ceramics",
  HERITAGE: "Heritage",
  "MODULAR CCA (C&S)": "Modular Cca (C&S)",
  "INNOVATORS' CLUB": "Innovators' Club",
  "SPEECH AND DRAMA": "Speech And Drama",
  "ENGLISH CULTURE AND LANGUAGE": "English Culture And Language",
  "LION AND DRAGON DANCE": "Lion And Dragon Dance",
  "CHINESE CHESS": "Chinese Chess",
  JOURNALISM: "Journalism",
  "DRAGON BOAT": "Dragon Boat",
  "AERO-MODELLING": "Aero-Modelling",
  "AUDIO VIDEO AND INFORMATION TECHNOLOGY CLUB":
    "Audio Video And Information Technology Club",
  HANDBALL: "Handball",
  "WESTERN ORCHESTRA": "Western Orchestra",
  "MARCHING BAND": "Marching Band",
  "NATIONAL POLICE CADET CORPS (SEA)": "National Police Cadet Corps (Sea)",
  "GAMELAN ENSEMBLE": "Gamelan Ensemble",
  "HEALTH AND FITNESS": "Health And Fitness",
  BROADCASTING: "Broadcasting",
  "DIKIR BARAT": "Dikir Barat",
  "CHINESE WEIQI": "Chinese Weiqi",
  "MODULAR CCA (VPA)": "Modular Cca (Vpa)",
  "TAP DANCE": "Tap Dance",
  BALLET: "Ballet",
  GYMNASTICS: "Gymnastics",
  MATHEMATICS: "Mathematics",
  ARCHERY: "Archery",
  "CIVIL DEFENCE": "Civil Defence",
  "COMMUNITY INVOLVEMENT CLUB": "Community Involvement Club",
  "COMMUNITY CLUB/YOUTH CLUB": "Community Club/Youth Club",
  "INTERNATIONAL AND GLOBAL STUDIES": "International And Global Studies",
  "ENSEMBLE -MIXED INSTRUMENT": "Ensemble -Mixed Instrument",
  "TECHNOLOGY CLUB": "Technology Club",
  "CHRISTIAN FELLOWSHIP": "Christian Fellowship",
  "ARTISTIC SWIMMING": "Artistic Swimming",
  "MEDIA RESOURCE AND IT CLUB": "Media Resource And It Club",
  SILAT: "Silat",
  "PIPE BAND": "Pipe Band",
  "FOOD AND CONSUMER EDUCATION": "Food And Consumer Education",
  "READING AND WRITING": "Reading And Writing",
  "SEA SPORTS": "Sea Sports",
  "CHESS CLUB - INTERNATIONAL": "Chess Club - International",
  "PHOTO AND VIDEO SOCIETY": "Photo And Video Society",
  "HARP ENSEMBLE": "Harp Ensemble",
  "CHINESE SOCIETY": "Chinese Society",
  CRICKET: "Cricket",
  "OPERA/OPERATTA": "Opera/Operatta",
  TRAMPOLINE: "Trampoline",
  DESIGN: "Design",
  "COMICS AND ILLUSTRATION": "Comics And Illustration",
  "SPACE SCIENCE": "Space Science",
  "INDIAN CULTURE AND LANGUAGE": "Indian Culture And Language",
  FILM: "Film",
  "CATHOLIC ACTIVITIES COUNCIL": "Catholic Activities Council",
  KARATE: "Karate",
  "INDIAN ORCHESTRA": "Indian Orchestra",
  "ECONOMICS SOCIETY": "Economics Society",
  "HORTICULTURE CLUB": "Horticulture Club",
  "JAPANESE CLUB": "Japanese Club",
  "OUTDOOR ACTIVITIES CLUB": "Outdoor Activities Club",
  "WRITERS' CIRCLE": "Writers' Circle",
  "CHINESE CALLIGRAPHY SOCIETY": "Chinese Calligraphy Society",
  "ANIMAL WELFARE SOCIETY": "Animal Welfare Society",
  "EARTH WATCH": "Earth Watch",
  "PA CREW": "Pa Crew",
  "STRATEGIC GAMES CLUB": "Strategic Games Club",
  "MEDICAL SOCIETY": "Medical Society",
  "COMPUTER CLUB": "Computer Club",
  "SCRABBLE CLUB": "Scrabble Club",
  "PROJECT CABIN": "Project Cabin",
};
